### ISSUE TITLE
 Key(s) not processed

### ISSUE THREAD

**Issue by Ixian** [edit4ever/script.module.sd4tvh#2]
Thanks for the script! Attempting to use it in standalone mode and getting a lot of errors like these:

`2019-01-03 02:22:42,261 root WARNING  Key(s) not processed for Program: hasSeriesArtwork
2019-01-03 02:22:42,261 root WARNING  Program metadata not processed: {u'TheTVDB': {u'seriesID': 71674, u'season': 0, u'episode': 0, u'episodeID': 0}}
2019-01-03 02:22:42,261 root WARNING  Key(s) not processed for Program: hasSeriesArtwork
2019-01-03 02:22:42,261 root WARNING  Program metadata not processed: {u'TheTVDB': {u'seriesID': 71674, u'season': 0, u'episode': 0, u'episodeID': 0}}
`
and 
`2019-01-03 01:12:05,489 root WARNING  Key(s) not processed for Station: stationLogo
2019-01-03 01:12:05,490 root WARNING  Key(s) not processed for Station: stationLogo
`

Suspect it might have something to do with channel filters? I don't know that it is picking up my hdhomerun. Trying this command:

`./sd2xmltv.py -u myuser -p mypass -o xmltv.xml -d 1 --hdhomerun 192.168.1.x`

Or "discover" in place of my hdhr ip doesn't seem to result in picking up the hdhr. I can access the lineup.json manually just fine. 

Is there something wrong with my command format? Or is there a way to disable the channel filters?

**Comment by edit4ever** [comment]
What are you seeing in the TVheadend log at the end of the run?

Also do are you using my script.module.sd4tvh or my sd2xmltv repo?
As an FYI - sd2xmltv was not my project - I forked atrilchuk's repo. However, I did rework into my own version which is the script.module.sd4tvh  - but that is meant to be an addon in kodi.

You may want to look at this as well: https://forum.kodi.tv/showthread.php?tid=307718

**Comment by Ixian** [comment]
This is at the end of the log 
`2019-01-03 01:12:54,633 sd2xmltv INFO     Added 36 programs for channel 54.1 KNVADT.
2019-01-03 01:12:54,634 sd2xmltv INFO     Added 1606 total programs.
2019-01-03 01:12:54,634 sd2xmltv INFO     Finished.`

It is getting programs (though the channels, at the top, don't get icon entries) so wondering if these are filter-related errors that can perhaps be ignored?

Re: tv_grab_zz_sdjson - that is what I was using, however, that grabber doesn't get program image links, and feedback from the developer indicates he's not too interested in adding it. I was hoping to use this instead, which seems like it would work, if I could figure out why channel icon links aren't retrieved/hdhr maps.

I am using your script; also tried atrilchuks.

Thanks!

**Comment by Ixian** [comment]
[sd4tvlog.txt](https://github.com/edit4ever/script.module.sd4tvh/files/2725893/sd4tvlog.txt)

[xmltv.xml.txt](https://github.com/edit4ever/script.module.sd4tvh/files/2725894/xmltv.xml.txt)

Attached my log, and the xmltv output. 
Looking through everything, I am wondering if these are just spurious log entries? Everything appears to be working, other than the channels are missing the logo entry i.e. they should be this:
`<channel id="I1111.58646.schedulesdirect.org">
    <display-name>CNNHD</display-name>
    <display-name>CNN HD</display-name>
    <display-name>1111 CNNHD</display-name>
    <display-name>1111</display-name>
    <icon src="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s58646_h3_ba.png" />`

But instead are this: 
`<channel id="I1111.58646.schedulesdirect.org">
 <display-name>1111 CNNHD</display-name>
 <display-name>1111</display-name>
 <display-name>CNNHD</display-name>
 <display-name>CNN HD</display-name>
</channel>`

But that I can probably live without since I can assign icons in TVHeadend. Just wondering if you see anything off with the filtering? I don't think it's connecting/pulling channels from my hdhr which maybe has something to do with it.

**Comment by edit4ever** [comment]
Ok - I can take a look and see in the next day or so. If you could get me the full log that would help. Sometimes I know in the past the server at SD has an issue...but let me see if something changed.

**Comment by Ixian** [comment]
When you say full log do you mean something else than what I posted? I don't think it's collecting another log?

**Comment by edit4ever** [comment]
That's the right data...just looking for the entire file.

**Comment by Ixian** [comment]
It's not this?

[sd4tvlog.txt](https://github.com/edit4ever/script.module.sd4tvh/files/2725999/sd4tvlog.txt)

**Comment by edit4ever** [comment]
Sorry - I was on my phone earlier and missed that you had posted those.  I will check them out and see what I can find.  Thanks!

**Comment by Ixian** [comment]
Appreciate you looking at this.

I am thinking, because I am using this outside of Kodi, and really leveraging atrilchuk's script, that it isn't anything in your package at all. 

I'm also thinking, after installing your addon in Kodi and looking at how it works, that the problem is I have no channel filter - for whatever reason, adding --hdhomerun 192.168.1.x (my hdhr) to the command line doesn't create a channel filter.

Do you have a sample channel filter file that I can reference? Since I have an m3u list of channels already from my hdhr (I wrote a simple script to get those) I am wondering, if I just create a file filter myself, it will do what your addon does with the file-based filter. If there's a way to invoke that from the cli I am thinking that might help.

**Comment by edit4ever** [comment]
I'm trying to go back and look at how all this works - it's been sometime!

Just want to check - you are using the files from my sd2xmltv repo not the ones from this repo right?

**Comment by Ixian** [comment]
Hey, 

I found: https://github.com/azlm8t/tv_grab_az_sdjson_sqlite

Which is a port of tv_grab_zz_sdjson_sqlite and does what I was looking for and then some when it comes to adding images and other metadata. I'm giving it a go since I don't use the Kodi addon to manage SD. Had no idea that project existed until today; it is well hidden.

Appreciate you looking at this and sorry if I wasted your time - perhaps I found a bug that needs fixing anyway?

**Comment by Ixian** [comment]
Also yes, was using your repo not the original sd2xmltv

**Comment by edit4ever** [comment]
Glad you foudn something that works - but I think the issue is that you were using the wrong set of files.  sd4tvh is for kodi use - but my sd2xmltv repo (forked from atrilchuk) is what you needed to be using.

anyway - the newer grabbers are likely more up to date and faster than this anyway.  Especially since tvheadend  keeps adding fields that can be populated.  Good luck!
